#!/bin/sh
target=".stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0/build/dostuff/dostuff"

do_ () {
	do_build
}

do_build () {
	stack build
}

do_clean () {
	stack clean
}

do_echo () {
	echo "$@"
}

do_test () {
	do_build
	for t in tests/*.sh; do
		echo -n "${t}: "
		if ${t} ${target} 2>/dev/null; then
			echo -e "\e[32msuccess\e[0m"
		else
			echo -e "\e[31mfailure\e[0m"
		fi
	done
}
