#!/bin/sh

do_() {
	echo "Nothing"
}

filetest() {
	echo $1
	echo $1 > dotest
	DOFILE="dotest" ./dostuff
	rm dotest
	echo
}

do_filetypes() {
	tup
	filetest '#!/bin/sh'
	filetest '#!/usr/bin/sh'
	filetest '#!/usr/bin/env sh'
	filetest '#!/bin/bash'
	filetest '#!/usr/bin/bash'
	filetest '#!/usr/bin/env bash'
	filetest '#!/bin/python'
	filetest '#!/usr/bin/python'
	filetest '#!/usr/bin/env python'
}

do_test() {
	tup
	test_generic "do-py"
	test_generic "do-sh"
	cp "do-sh" "../../do-rec"
	test_generic "do-rec"
	rm "../../do-rec"
}


test_generic() {
	echo "================"
	DOFILE="$1" ./dostuff
	DOFILE="$1" ./dostuff "test"
	DOFILE="$1" ./dostuff args 1 2 4 8
	DOFILE="$1" ./dostuff -f
}
